// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzRaMFac7P5_5QhvyTi4us9GwTlEOE0xw',
    appId: '1:328830802547:android:c664a4a4f0110a5dbc6806',
    messagingSenderId: '328830802547',
    projectId: 'food-app1910',
    storageBucket: 'food-app1910.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA6mEE5W-ThHHQomuULG5hJB3KIVnJ1Ds',
    appId: '1:328830802547:ios:b2e9312e945d87fcbc6806',
    messagingSenderId: '328830802547',
    projectId: 'food-app1910',
    storageBucket: 'food-app1910.appspot.com',
    iosClientId: '328830802547-sc2jihob1ppdmas622rv3a13gk1lfqhv.apps.googleusercontent.com',
    iosBundleId: 'com.juliaczaplejewicz.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA6mEE5W-ThHHQomuULG5hJB3KIVnJ1Ds',
    appId: '1:328830802547:ios:b2e9312e945d87fcbc6806',
    messagingSenderId: '328830802547',
    projectId: 'food-app1910',
    storageBucket: 'food-app1910.appspot.com',
    iosClientId: '328830802547-sc2jihob1ppdmas622rv3a13gk1lfqhv.apps.googleusercontent.com',
    iosBundleId: 'com.juliaczaplejewicz.foodApp',
  );
}
